#!/usr/bin/env bash
set -euo pipefail
private_root=/home/reefshark/research/agent_os/ic_bcmk_eval_private
export T10_SPATIAL_SOURCE_VARIANT=ic_t10_candidate_top_v108_distributed_synth_m7_wc_p1000_seed11
export T10_FLOW_VARIANT=ic_t10_candidate_top_v115_distributed_control_local_m7_wc_p1000_seed11
export T10_DISTRIBUTED_EGRESS=1
bash "$private_root/physical/run_t10_transport_spatial_probe.sh"
export T10_CHECK_VARIANT=$T10_FLOW_VARIANT
bash "$private_root/physical/run_t10_transport_spatial_checks.sh"
export T10_INTERFACE_SOURCE_VARIANT=$T10_FLOW_VARIANT
export T10_FLOW_VARIANT=ic_t10_candidate_top_v116_distributed_local_interfaces_m7_wc_p1000_seed11
bash "$private_root/physical/run_t10_transport_interface_probe.sh"
export T10_SOURCE_VARIANT=$T10_FLOW_VARIANT
export T10_FLOW_VARIANT=ic_t10_candidate_top_v117_distributed_local_signals_m7_wc_p1000_seed11
export T10_REPAIR_ALL_SIGNALS=1
export T10_REPAIR_ROOT_BUFFER=1
export T10_REPAIR_SPACING_UM=150
export T10_REPAIR_THRESHOLD_UM=200
bash "$private_root/physical/run_t10_top_data_control_repair.sh"
export T10_CHECK_VARIANT=$T10_FLOW_VARIANT
export T10_CHECK_INPUT_ODB=/mnt/ubu_3T/ic_bcmk_orfs_asap7/flow/results/asap7/npu_systolic_matmul_16x16/$T10_FLOW_VARIANT/4_cts_clock_repair_pending.odb
bash "$private_root/physical/run_t10_transport_spatial_checks.sh"
