export PLATFORM = asap7
export DESIGN_NAME = t10_reference_cpa_postprocess
export VERILOG_FILES = /home/reefshark/research/agent_os/ic_bcmk_eval_private/refs/T10/rtl/npu_systolic_matmul_16x16.sv
export SDC_FILE = /home/reefshark/research/agent_os/ic_bcmk_eval_private/physical/t10_frozen_cpa_postprocess/constraint.sdc
export CORE_UTILIZATION = 42
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 0.5
export PLACE_DENSITY = 0.42
export SYNTH_USE_SYN = 0
export SYNTH_HIERARCHICAL = 0
export CORNER = WC
export GPL_ROUTABILITY_DRIVEN = 0
export SYNTH_BLACKBOXES =
export ADDITIONAL_LEFS =
export ADDITIONAL_LIBS =
export PDN_TCL = /home/reefshark/research/agent_os/ic_bcmk_eval_private/physical/t10_frozen_int_group/pdn.tcl
export PRE_CTS_TCL = /home/reefshark/research/agent_os/ic_bcmk_eval_private/physical/t10_frozen_int_group/pre_cts_m6_m7.tcl
export IO_PLACER_H = M6
export MAX_ROUTING_LAYER = M7
export MIN_CLK_ROUTING_LAYER = M6
export ROUTING_LAYER_ADJUSTMENT = 0
export SKIP_INCREMENTAL_REPAIR = 1
export CTS_CLUSTER_SIZE = 64
export CTS_CLUSTER_DIAMETER = 100
export CTS_ARGS = -sink_clustering_enable -repair_clock_nets -sink_clustering_size 64 -sink_clustering_max_diameter 100 -no_insertion_delay
export SKIP_CTS_REPAIR_TIMING = 1
export GRT_SEED = $(T10_LAYOUT_SEED)
export OR_SEED = $(T10_LAYOUT_SEED)
